spring.application.name=campus-hiring-evaluation

spring.datasource.url=jdbc:mysql://localhost:3306/vehicle_database?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=37799

spring.cache.type=simple

logging.level.com.vehicle=DEBUG
logging.level.org.springframework.web=INFO

external.api.email=2300032558cseelge@gmail.com
external.api.name=dhiravathu bhargav sai
external.api.rollNo=2300032558
external.api.accessCode=AvrAAK
external.api.clientID=c4645cc2-4944-4a44-9c82-c4493eea9583
external.api.clientSecret=MnEGrYSZzVsUMkcq
